version: "3.9"
services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=e_learning_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toto



  app:
    restart: always
    build: .
    image: e_learning_project:1.0
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app

volumes:
  db_data: {}
